name: Update Repo Age Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install jq

      - name: Make script executable
        run: chmod +x .github/workflows/update_repo_age.sh
  

      - name: Run repo age update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: bash .github/workflows/update_repo_age.sh

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "update: update readme" -m "This action was done by a bot." -m "" -m "Signed-off-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>" -m "Co-authored-by: BenzoiTheCoder <benzoi9312@gmail.com>"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
